### ISSUE TITLE
ClueGaudiAlgorithmWrapper in nightlies not found

### ISSUE THREAD

**Issue by ebrondol** [key4hep/k4Clue#46]
After sourcing the nightlies and running the 'ClueGaudiAlgorithmWrapper', this is not found:
```
Traceback (most recent call last):
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-08-07/x86_64-centos7-gcc12.2.0-opt/k4fwcore/338f4ec16d29a8e0d2b2ae98ea781d06fa62d7a8=develop-wmlbp3/bin/k4run", line 124, in <module>
    opts = parser.parse_known_args()
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-24/x86_64-centos7-gcc12.2.0-opt/python/3.10.10-jyeoxq/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-24/x86_64-centos7-gcc12.2.0-opt/python/3.10.10-jyeoxq/lib/python3.10/argparse.py", line 2054, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-24/x86_64-centos7-gcc12.2.0-opt/python/3.10.10-jyeoxq/lib/python3.10/argparse.py", line 2031, in consume_positionals
    take_action(action, args)
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-06-24/x86_64-centos7-gcc12.2.0-opt/python/3.10.10-jyeoxq/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-08-07/x86_64-centos7-gcc12.2.0-opt/k4fwcore/338f4ec16d29a8e0d2b2ae98ea781d06fa62d7a8=develop-wmlbp3/bin/k4run", line 45, in __call__
    exec(open(wrapper.name).read(), globals())
  File "<string>", line 1768, in <module>
ImportError: cannot import name 'ClueGaudiAlgorithmWrapper' from 'Gaudi.Configurables' (unknown location)
```
The error does not appear in case I source an old version of the stack (key4hep-stack/2023-04-08) with:
`source /cvmfs/sw.hsf.org/key4hep/setup.sh`

**Comment by ebrondol** [comment]
Solved with https://github.com/key4hep/key4hep-spack/pull/515
